seed: 0
model_class: BasicCNN
dataset_name: mnist
dataset_train_frac: 0.8
dataset_test_frac: 0.1
dataset_val_frac: 0.1
loss_fn: CrossEntropy
hp_opt_name: Adam
hp_optarg_lr: 0.002
hp_epochs: 4
hp_batch_size: 64
log_dots: "[4, 16, 64]"
log_datadots: "[4, 16, 64]"
log_accuracy: True