seed: 1
model_class: MLP
modelarg_in_size: 2
modelarg_out_size: 2
modelarg_hidden: "[128, 128]"
dataset_name: randtwoclasses
dataset_train_frac: 0.8
dataset_test_frac: 0.1
dataset_val_frac: 0.1
loss_fn: CrossEntropy
hp_opt_name: Adam
hp_optarg_lr: 0.05
hp_epochs: 20
hp_batch_size: 16
log_dots: "[4, 16]"
log_datadots: "[4, 16]"
log_accuracy: True