program: run.py
method: random
metric:
  name: test_loss
  goal: minimize
parameters:
  seed:
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
  model_class: 
    value: MLP
  modelarg_in_size:
    value: 1
  modelarg_hidden: 
    values:
      - "[8]"
      - "[64]"
      - "[512]"
      - "[8, 8]"
      - "[8, 8, 8]"
      - "[8, 8, 8, 8]"
      - "[32]"
      - "[32, 32]"
      - "[32, 32, 32]"
  modelarg_out_size: 
    value: 1
  modelarg_bias: 
    value: true
  dataset_name: 
    value: sin
  dataset_train_frac:
    value: 0.8
  dataset_test_frac:
    value: 0.1
  dataset_val_frac:
    value: 0.1
  loss_fn:
    value: MSELoss
  hp_opt_name:
    value: Adam
  hp_optarg_lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
  hp_epochs:
    value: 30
  hp_batch_size:
    values:
      - 64
  log_dots:
    value: "[32, 128, 1024]"
  log_datadots:
    value: "[32, 128, 1024]"
  log_trainstate_datasize:
    value: 1024
  log_trainstate_randsize:
    value: "[1024, 8192]"