program: run.py
method: random
metric:
  name: test_acc
  goal: maximize
parameters:
  seed:
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
  model_class: 
    values:
      - BasicCNN
  dataset_name: 
    value: mnist
  dataset_train_frac:
    value: 0.8
  dataset_test_frac:
    value: 0.1
  dataset_val_frac:
    value: 0.1
  loss_fn:
    value: CrossEntropy
  hp_opt_name:
    values:
      - Adam
      - SGD
  hp_optarg_lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
  hp_epochs:
    value: 2
  hp_batch_size:
    values:
      - 64
  log_dots:
    value: "[768, 2048]"
  log_datadots:
    value: "[768, 2048]"
  log_accuracy:
    value: True