program: run.py
method: random
metric:
  name: test_acc
  goal: maximize
parameters:
  seed:
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
  model_class: 
    values:
      - MLP
  modelarg_in_size:
    value: 2
  modelarg_out_size:
    value: 2
  modelarg_hidden: 
    values:
      - "[1024]"
      - "[4096]"
      - "[12, 12, 12]"
      - "[24, 24, 24]"
      - "[128, 128]"
      - "[128, 128, 128]"
  dataset_name: 
    value: randtwoclassesHARD
  dataset_train_frac:
    value: 1.0
  dataset_test_frac:
    value: 0.0
  dataset_val_frac:
    value: 0.0
  loss_fn:
    value: CrossEntropy
  hp_opt_name:
    values:
      - SGD
      - Adam
  hp_optarg_lr:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.4
  hp_epochs:
    value: 2000
  hp_batch_size:
    values:
      - 1
  log_dots:
    value: "[64, 512]"
  log_datadots:
    value: "[16, 40, 100]"
  log_every_n_epochs:
    value: 100
  log_accuracy:
    value: True